name: Build Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Pull a JavaFX JDK
      run: wget http://static.azul.com/zulu/bin/zulu8.33.0.1-ca-fx-jdk8.0.192-linux_x64.tar.gz

    - name: Set Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        jdkFile: ./zulu8.33.0.1-ca-fx-jdk8.0.192-linux_x64.tar.gz

    - name: Build fatJar
      run: ./gradlew fatJar

    - name: Shrink with ProGuard
      run: |
        ./gradlew proguard
        mv build/libs/QuestionPool-1.1-proguard.jar build.jar

    - name: Create artifact
      uses: actions/upload-artifact@master
      with:
        name: build_artifact
        path: build.jar
