name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: curl -O "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09/OpenJDK8U-jdk_x64_linux_hotspot_8u232b09.tar.gz"
    - name: Set Java
      uses: actions/setup-java@master
      with:
        version: 9
        architecture: x64
        jdkFile: ./OpenJDK8U-jdk_x64_linux_hotspot_8u232b09.tar.gz
    - name: Build fatJar
      run: ./gradlew fatJar
    - name: Shrink with ProGuard
      run: ./gradlew proguard
